name: final_activity
description: "A school mailing application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.4.2
  liquid_glass_widgets: ^0.24.4
  skeletonizer: ^2.1.0
  http: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true